device: 'cuda'
checkpoint_load:
checkpoint_save:
log:
log_file_name:
data_root: 'data/'

dataset: 'VGGFace2'
num_classes: 170
input_height: 
input_width:
input_channel:

epochs: 100
batch_size: 64
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR

poison_rate: 0.1
target_type: 'all2one'
target_label: 0

model: 'pretrvgg16'
seed: 33333
index: 

ratio: 0.05

