amp: False
device: cuda:0

client_optimizer: sgd
frequency_save: 100
batch_size: 128
lr: 0.01
lr_scheduler: MultiStepLR
steplr_milestones: 100 150
steplr_gamma: 0.1
random_seed: 0
sgd_momentum: 0.9
wd: 0.0005
epochs: 200
model: resnet18
pratio: 0.1

dataset: cifar10
dataset_path: ../data
val_frac: 0.1
attack_label_trans: all2one
attack_target: 0
attack: fix_patch

patch_mask_path: ../resource/badnet/cifar10_bottom_right_3by3_blackwhite.npy

